[package]
name = "experiments"
version = "0.1.0"
authors = ["manpat <pat@patsown.com>"]
build = "build.rs"

[dependencies]
common = { git = "https://github.com/manpat/common-rs.git" }
# common = { path = "../common" }
